In [26]:
import generator as gen

# PYTHON NUMPY MODEL

## XOR MODEL

In [125]:
# H5_PATH = 'cmt_model/xor.h5'
H5_PATH = 'sep_model/xor/weights.h5'
JSON_PATH = 'sep_model/xor/model.json'
# JSON_PATH = None

l_results = gen.get_model_data(h5_path = H5_PATH,json_path = JSON_PATH)

if l_results:
    l_w, l_b, l_a = l_results
    str_code = gen.get_py_code(l_w, l_b, l_a)
    exec(str_code)

    x_test = np.array([[0,0],[0,1],[1,0],[1,1]])
    model = Model()
    pred = model.pred(x_test)
    print(pred)

[[ 0.09024292]
 [ 1.1006538 ]
 [ 1.32896663]
 [-0.35731253]]


## IRIS MODEL

In [117]:
H5_PATH = 'cmt_model/iris.h5'
JSON_PATH = None

H5_PATH = 'sep_model/iris/weights.h5'
JSON_PATH = 'sep_model/iris/model.json'

l_results = gen.get_model_data(h5_path = H5_PATH,json_path = JSON_PATH)

if l_results:
    l_w, l_b, l_a = l_results
    str_code = gen.get_py_code(l_w, l_b, l_a)
    exec(str_code)

    x_test = np.array([[0.39, 0.38, 0.54, 0.5], [0.11, 0.5, 0.1, 0.04], [0.61, 0.33, 0.61, 0.58]])
    model = Model()
    pred = model.pred(x_test)
    print(pred.round().astype(int))

[[0 1 0]
 [1 0 0]
 [0 1 0]]


# JAVASCRIPT MODEL

In [144]:
H5_PATH = 'cmt_model/xor.h5'
# H5_PATH = 'sep_model/xor/weights.h5'
# JSON_PATH = 'sep_model/xor/model.json'
# JSON_PATH = None

l_results = gen.get_model_data(h5_path = H5_PATH, json_path = JSON_PATH)

if l_results:
    l_w, l_b, l_a = l_results
    str_code = gen.get_js_code(l_w, l_b, l_a)
    
    file = open('js_model/model.js','w')
    file.write(str_code)
    file.close()
print('\nFinished')


Finished
